// <auto-generated />
namespace Code_First_Tutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SeedingRolesData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedingRolesData));
        
        string IMigrationMetadata.Id
        {
            get { return "202203101214373_SeedingRolesData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
